\x1b[1m========================================================================== test session starts ===========================================================================\x1b[0m\nplatform darwin -- Python 3.10.5, pytest-7.2.0.dev251+gd9d890ee1, pluggy-1.0.0 -- /Users/jwr003/coding/pytest-tui/venv/bin/python\ncachedir: .pytest_cache\nmetadata: {\'Python\': \'3.10.5\', \'Platform\': \'macOS-12.4-x86_64-i386-64bit\', \'Packages\': {\'pytest\': \'7.2.0.dev251+gd9d890ee1\', \'py\': \'1.11.0\', \'pluggy\': \'1.0.0\'}, \'Plugins\': {\'rerunfailures\': \'10.2\', \'html\': \'3.1.1\', \'clarity\': \'1.0.1\', \'Faker\': \'13.15.1\', \'metadata\': \'2.0.2\', \'tui\': \'1.2.1\'}, \'JAVA_HOME\': \'/Users/jwr003/Library/Java/JavaVirtualMachines/corretto-11.0.12/Contents/Home\'}\nrootdir: /Users/jwr003/coding/pytest-tui, configfile: pytest.ini\nplugins: rerunfailures-10.2, html-3.1.1, clarity-1.0.1, Faker-13.15.1, metadata-2.0.2, tui-1.2.1\n\x1b[1mcollecting ... \x1b[0m\x1b[1m\ncollected 63 items / 55 deselected / 8 selected                                                                                                                          \x1b[0m\n\ndemo-tests/test_0.py::test0_pass_1 \x1b[32mPASSED\x1b[0m\x1b[32m                                                                                                                          [ 12%]\x1b[0m\ndemo-tests/test_0.py::test0_pass_2_logs \x1b[32mPASSED\x1b[0m\x1b[32m                                                                                                                     [ 25%]\x1b[0m\ndemo-tests/test_0.py::test0_pass_3_error_in_fixture \x1b[31mERROR\x1b[0m\x1b[31m                                                                                                          [ 37%]\x1b[0m\ndemo-tests/test_0.py::test0_fail_1 \x1b[31mFAILED\x1b[0m\x1b[31m                                                                                                                          [ 50%]\x1b[0m\ndemo-tests/test_0.py::test0_skip \x1b[32mPASSED\x1b[0m\x1b[31m                                                                                                                            [ 62%]\x1b[0m\ndemo-tests/test_0.py::test0_xfail \x1b[33mXFAIL\x1b[0m\x1b[31m                                                                                                                            [ 75%]\x1b[0m\ndemo-tests/test_0.py::test0_xpass \x1b[33mXPASS\x1b[0m\x1b[31m                                                                                                                            [ 87%]\x1b[0m\ndemo-tests/test_0.py::test0_warning \x1b[32mPASSED\x1b[0m\x1b[31m                                                                                                                         [100%]\x1b[0m\n\n================================================================================= ERRORS =================================================================================\n\x1b[31m\x1b[1m____________________________________________________________ ERROR at setup of test0_pass_3_error_in_fixture _____________________________________________________________\x1b[0m\n\n    \x1b[37m@pytest\x1b[39;49;00m.fixture\n    \x1b[34mdef\x1b[39;49;00m \x1b[92merror_fixt\x1b[39;49;00m():\n>       \x1b[34mraise\x1b[39;49;00m \x1b[96mException\x1b[39;49;00m(\x1b[33m"\x1b[39;49;00m\x1b[33mError in fixture\x1b[39;49;00m\x1b[33m"\x1b[39;49;00m)\n\x1b[1m\x1b[31mE       Exception: Error in fixture\x1b[0m\n\n\x1b[1m\x1b[31mdemo-tests/test_0.py\x1b[0m:27: Exception\n================================================================================ FAILURES ================================================================================\n\x1b[31m\x1b[1m______________________________________________________________________________ test0_fail_1 ______________________________________________________________________________\x1b[0m\n\n    \x1b[34mdef\x1b[39;49;00m \x1b[92mtest0_fail_1\x1b[39;49;00m():\n        \x1b[96mprint\x1b[39;49;00m(\x1b[33m"\x1b[39;49;00m\x1b[33mTest Fail 1!\x1b[39;49;00m\x1b[33m"\x1b[39;49;00m)\n>       \x1b[34massert\x1b[39;49;00m \x1b[34m1\x1b[39;49;00m == \x1b[34m2\x1b[39;49;00m\n\x1b[1m\x1b[31mE       assert 1 == 2\x1b[0m\n\n\x1b[1m\x1b[31mdemo-tests/test_0.py\x1b[0m:37: AssertionError\n-------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------\nTest Fail 1!\n\x1b[33m============================================================================ warnings summary ============================================================================\x1b[0m\ndemo-tests/test_0.py::test0_warning\n  /Users/jwr003/coding/pytest-tui/demo-tests/test_0.py:59: UserWarning: api v1, should use functions from v2\n    warnings.warn(UserWarning("api v1, should use functions from v2"))\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n================================================================================= PASSES =================================================================================\n\x1b[32m\x1b[1m______________________________________________________________________________ test0_pass_1 ______________________________________________________________________________\x1b[0m\n-------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------\nTest Pass 1!\n\x1b[32m\x1b[1m___________________________________________________________________________ test0_pass_2_logs ____________________________________________________________________________\x1b[0m\n-------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------\nTest Pass 2!\nCRITICAL\nCRITICAL\nCRITICAL\nERROR\nERROR\nERROR\nWARNING\nWARNING\nWARNING\nINFO\nINFO\nINFO\nDEBUG\nDEBUG\nDEBUG\n--------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------\n\x1b[31mCRITICAL\x1b[0m root:test_0.py:17 CRITICAL\n\x1b[1m\x1b[31mERROR   \x1b[0m root:test_0.py:18 ERROR\n\x1b[33mWARNING \x1b[0m root:test_0.py:19 WARNING\n\x1b[32mINFO    \x1b[0m root:test_0.py:20 INFO\n\x1b[35mDEBUG   \x1b[0m root:test_0.py:21 DEBUG\n\x1b[36m\x1b[1m======================================================================== short test summary info =========================================================================\x1b[0m\n\x1b[32mPASSED\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_pass_1\x1b[0m\n\x1b[32mPASSED\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_pass_2_logs\x1b[0m\n\x1b[32mPASSED\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_skip\x1b[0m\n\x1b[32mPASSED\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_warning\x1b[0m\n\x1b[33mXFAIL\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_xfail\x1b[0m\n\x1b[33mXPASS\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_xpass\x1b[0m \n\x1b[31mERROR\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_pass_3_error_in_fixture\x1b[0m - Exception: Error in fixture\n\x1b[31mFAILED\x1b[0m demo-tests/test_0.py::\x1b[1mtest0_fail_1\x1b[0m - assert 1 == 2\n\x1b[31m========================================== \x1b[31m\x1b[1m1 failed\x1b[0m, \x1b[32m4 passed\x1b[0m, \x1b[33m55 deselected\x1b[0m, \x1b[33m1 xfailed\x1b[0m, \x1b[33m1 xpassed\x1b[0m, \x1b[33m1 warning\x1b[0m, \x1b[31m\x1b[1m1 error\x1b[0m\x1b[31m in 1.21s\x1b[0m\x1b[31m ==========================================\x1b[0m\n
